apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: prod-project-sync
    description: The "prod" will be applied to the `devops` group.
    groups:
    - devops
    policies:
    - p, proj:prod:prod-project-sync, applications, get, *, allow
    - p, proj:prod:prod-project-sync, applications, sync, *, allow
    
